version: "3.7"

services:
  postgres:
    image: postgres:14.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    command: server /data
    restart: always
    ports:
      - "9000:9000"
    env_file:
      - ./.env.dev
    volumes:
      - ./data/minio/data:/data
      - ./data/minio/config:/root/.minio

volumes:
  postgres_data: